name: Build and Deploy

on:
    push:
    workflow_call:
        inputs:
            deploy:
                required: false
                type: boolean
                default: false

jobs:
    build:
        if: ${{ !contains(github.event.head_commit.message, 'skip ci') || !contains(github.event.head_commit.message, 'ci-push') }}
        uses: ./.github/workflows/build.yml
        secrets: inherit

    deploy:
        needs: [build]
        if: github.repository_owner == 'LSS-Manager' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || inputs.deploy)
        uses: ./.github/workflows/deploy.yml
        with:
            branch: needs.build.outputs.branch
        secrets: inherit