name: Deploy Request

on:
    issue_comment:
        types:
            - created

jobs:
    check_request:
        runs-on: ubuntu-latest
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '@LSS-Manager deploy' }}
        outputs:
            deploy: ${{ steps.get_maintainers.outputs.deploy }}
        steps:
            - name: '[🧑‍💻] get maintainers'
              id: get_maintainers
              run: |
                  isTeamMember="$(gh api graphql -F owner=$OWNER -F team=$TEAM -f query='
                    query($owner: String!, $team: String!) {
                      organization(login: $owner) {
                        team(slug: $team) {
                          members {
                            nodes {
                              login
                            }
                          }
                        }
                      }
                    }' --jq '.data.organization.team.members.nodes[].login' | grep $AUTHOR | wc -l)"

                  echo "deploy=$(if [[ $isTeamMember == 0 ]]; then echo false; else echo true; fi)" >> $GITHUB_OUTPUT
              env:
                  GITHUB_TOKEN: ${{ secrets.CHECK_MAINTAINERS_TOKEN }}
                  OWNER: ${{ github.repository_owner }}
                  TEAM: 'v4-maintainers'
                  AUTHOR: ${{ github.event.comment.user.login }}

    react_to_request:
        runs-on: ubuntu-latest
        needs: [check_request]
        if: ${{ needs.check_request.outputs.deploy == 'true' }}
        steps:
            - name: '[👍️️] react to the request'
              run: |
                  gh api --method POST -H "Accept: application/vnd.github+json" /repos/$REPO/comments/$COMMENT/reactions -f content='+1'
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  COMMENT: ${{ github.event.comment.id }}
                  REPO: ${{ github.repository }}

    build_and_deploy:
        needs: [check_request]
        if: ${{ needs.check_request.outputs.deploy == 'true' }}
        uses: ./.github/workflows/build-deploy.yml
        with:
            deploy: ${{ needs.check_request.outputs.deploy == 'true' }}
        secrets: inherit