name: Deploy Request

on:
    issue_comment:
        types:
            - created

jobs:
    check_request:
        runs-on: ubuntu-latest
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '@LSS-Manager deploy' }}
        outputs:
            deploy: ${{ steps.get_maintainers.outputs.deploy }}
        steps:
            - name: '[🧑‍💻] get maintainers'
              id: get_maintainers
              run: |
                  isTeamMember="$(gh api graphql -F owner=$OWNER -F team=$TEAM -f query='
                    query($owner: String!, $team: String!) {
                      organization(login: $owner) {
                        team(slug: $team) {
                          members {
                            nodes {
                              login
                            }
                          }
                        }
                      }
                    }' --jq '.data.organization.team.members.nodes[].login' | grep $AUTHOR | wc -l)"

                  echo "deploy=$(if [[ $isTeamMember == 0 ]]; then echo false; else echo true; fi)" >> $GITHUB_OUTPUT
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_REQUEST_TOKEN }}
                  OWNER: ${{ github.repository_owner }}
                  TEAM: 'v4-maintainers'
                  AUTHOR: ${{ github.event.comment.user.login }}

    react_to_request:
        runs-on: ubuntu-latest
        needs: [check_request]
        if: ${{ needs.check_request.outputs.deploy == 'true' }}
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: '[👍️️] react to the request'
              run: |
                  gh api --method POST -H "Accept: application/vnd.github+json" /repos/$REPO/comments/$COMMENT/reactions -f content='+1'
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_REQUEST_TOKEN }}
                  COMMENT: ${{ github.event.comment.id }}
                  REPO: ${{ github.repository }}

    build:
        needs: [check_request]
        if: ${{ needs.check_request.outputs.deploy == 'true' }}
        uses: ./.github/workflows/build.yml
        with:
            ref: refs/pull/${{ github.event.issue.number }}/merge
        secrets: inherit

    deploy:
        needs: [build]
        uses: ./.github/workflows/deploy.yml
        with:
            branch: ${{ needs.build.outputs.branch }}
        secrets: inherit

    reply_to_request:
        runs-on: ubuntu-latest
        needs: [deploy]
        steps:
            - name: '[💬] reply to the request'
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.DEPLOY_REQUEST_TOKEN }}
                  script: |
                      github.issues.createComment({
                        issue_number: ${{ github.event.issue.number }},
                        owner: ${{ github.repository_owner }},
                        repo: 'LSSM-V.4',
                        body: '👍️ I have successfully deployed a build!'
                      })