name: '[👷🔀] PR Build'
run-name: '[👷🔀] Build on PR #${{ github.event.number }}, `${{ github.ref }}`'

on: [pull_request]

jobs:
    build:
        name: '[👷🔀] Build'
        uses: ./.github/workflows/build.yml
        with:
            ref: ${{ github.ref }}
        secrets: inherit

    test:
        name: '[👷🔀] Test'
        uses: ./.github/workflows/test_build.yml
        with:
            ref: ${{ github.ref }}
        secrets: inherit

    success:
        name: '[👷🔀] Success'
        needs: [build, test]
        if: ${{ success() }}
        run: |
            echo "🥳 Build and test successful!"