name: '[🧪] Test build'
run-name: '[🧪] Test build on `${{ github.ref }}`'

on:
    push:
    pull_request:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}
        name: '[🧪] Test Build on ${{ matrix.os }}'
        steps:
            - name: '[📥] checkout'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '[👷] run build script'
              run: |
                  ./build/build.sh --full